apiVersion: v1
kind: Service
metadata:
  name: online-course-platform
spec:
  selector:
    app: online-course-platform
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4200
  type: NodePort